### ISSUE TITLE
Doesn't work with pylint 1.5.0 / astroid 1.4.0

### ISSUE THREAD

**Issue by jribbens** [landscapeio/pylint-django#51]
```
  File "lib/python3.4/site-packages/pylint_django/utils.py", line 3, in <module>
    from astroid.bases import YES, Instance
ImportError: cannot import name 'YES'
```
If I fix that then:
```
  File "lib/python3.4/site-packages/pylint/lint.py", line 486, in load_plugin_modules
    module.register(self)
  File "lib/python3.4/site-packages/pylint_django/plugin.py", line 34, in register
    apply_augmentations(linter)
  File "lib/python3.4/site-packages/pylint_django/augmentations/__init__.py", line 300, in apply_augmentations
    augment_visit(linter, TypeChecker.visit_getattr, foreign_key_sets)
AttributeError: type object 'TypeChecker' has no attribute 'visit_getattr'
```

**Comment by carlio** [comment]
Seems this is an upstream bug in pylint, I created an issue here: https://bitbucket.org/logilab/pylint/issues/711/new-node-visit-methods-not-backwards

**Comment by carlio** [comment]
Well, not entirely true - pylint methods were renamed but the backwards-compatability logic seems to have a bug. I have updated this plugin to use the new names but will wait a little to see if it's possible to keep using the old ones too, as otherwise the next `pylint-django` release will only be compatible with `pylint>=1.5`

**Comment by golem131** [comment]
Traceback (most recent call last):
  File "/Users/ppetlinsky/Envs/py34/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/lint.py", line 1315, in __init__
    linter.check(args)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/lint.py", line 734, in check
    self._do_check(files_or_modules)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/lint.py", line 865, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/lint.py", line 945, in check_astroid_module
    walker.walk(ast_node)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/utils.py", line 938, in walk
    self.walk(child)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/utils.py", line 935, in walk
    cb(astroid)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/checkers/stdlib.py", line 192, in visit_call
    self._check_deprecated_method(node, inferred)
  File "/Users/ppetlinsky/Envs/py34/lib/python3.4/site-packages/pylint/checkers/stdlib.py", line 225, in _check_deprecated_method
    qname = infer.qname()
AttributeError: 'ImportFrom' object has no attribute 'qname'

**Comment by carlio** [comment]
The latest version on the `master` branch is working now for Python 2.7. For Python 3.x there seems to be a bug in astroid/pylint which I'm tracking down now.

**Comment by carlio** [comment]
`0.7` just released on pypi, should have all these issues fixed.

**Comment by jribbens** [comment]
Thanks, it seems much better, however the following test script produces an error when linted and it seems to me that it should not:
```python
"""Test case."""
from django.contrib.auth.models import User
User.objects.get(email="hello", password="there")
```
`E:  3, 0: Instance of 'UserManager' has no 'get' member (no-member)`

(This is with Python 3.4.3, Django 1.8.7, django-cms 3.2.0, pylint 1.5.0, astroid 1.4.1, pylint-django 0.7.)

**Comment by abaldwin1** [comment]
I also see an error similar to what jribbens describes.

```python
pylint --load-plugins=pylint_django -E ./

[... pylint output]
Instance of 'User' has no 'filter' member (no-member)
```

(Python 2.7.6, Django 1.6.11, pylint 1.5.2, astroid 1.4.3, pylint-django 0.7.1)
