### ISSUE TITLE
'Module' object has no attribute '_locals'

### ISSUE THREAD

**Issue by Alexx-G** [landscapeio/pylint-django#55]
And seems like it's happening because of this import
```python
from django.utils.translation import ugettext_lazy as _
```

Here's the traceback:

 File "/..../lib/python3.4/site-packages/astroid/manager.py", line 337, in transform
    ret = transform_func(node)
  File "/..../lib/python3.4/site-packages/pylint_django/transforms/__init__.py", line 29, in set_fake_locals
    module._locals[class_name] = fake._locals[class_name]  # pylint: disable=protected-access
AttributeError: 'Module' object has no attribute '_locals'

Pylint and python version:
pylint 1.4.4, 
astroid 1.3.8, common 1.1.0
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1]

**Comment by meteor5118** [comment]
I also encounter same problem in Windows.
astroid (1.3.8)
Django (1.8.7)
pylint (1.4.4)
pylint-django (0.7.1)
pylint-plugin-utils (0.2.3)

Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pylint.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\pylint\__init__.py", line 23, in run_pylint
    Run(sys.argv[1:])
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 1332, in __init__
    linter.check(args)
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 747, in check
    self._do_check(files_or_modules)
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 869, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "C:\Python27\lib\site-packages\pylint\lint.py", line 946, in check_astroid_module
    walker.walk(ast_node)
  File "C:\Python27\lib\site-packages\pylint\utils.py", line 874, in walk
    self.walk(child)
  File "C:\Python27\lib\site-packages\pylint\utils.py", line 871, in walk
    cb(astroid)
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 54, in augment_func
    augmentation(chain, node)
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 127, in do_suppress
    chain()
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 53, in chain
    old_method(node)
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 54, in augment_func
    augmentation(chain, node)
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 127, in do_suppress
    chain()
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 53, in chain
    old_method(node)
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 54, in augment_func
    augmentation(chain, node)
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 127, in do_suppress
    chain()
  File "C:\Python27\lib\site-packages\pylint_plugin_utils\__init__.py", line 53, in chain
    old_method(node)
  File "C:\Python27\lib\site-packages\pylint\checkers\classes.py", line 320, in visit_class
    self._check_bases_classes(node)
  File "C:\Python27\lib\site-packages\pylint\checkers\classes.py", line 811, in _check_bases_classes
    unimplemented_abstract_methods(node, is_abstract).items(),
  File "C:\Python27\lib\site-packages\pylint\checkers\utils.py", line 544, in unimplemented_abstract_methods
    infered = safe_infer(obj)
  File "C:\Python27\lib\site-packages\pylint\checkers\utils.py", line 92, in safe_infer
    value = next(inferit)
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 124, in _infer_stmts
    for infered in stmt.infer(context):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 86, in cache_generator
    for result in generator:
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 124, in _infer_stmts
    for infered in stmt.infer(context):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 86, in cache_generator
    for result in generator:
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\inference.py", line 229, in infer_from
    module = self.do_import_module()
  File "C:\Python27\lib\site-packages\astroid\mixins.py", line 107, in do_import_module
    return mymodule.import_module(modname, level=level)
  File "C:\Python27\lib\site-packages\astroid\scoped_nodes.py", line 431, in import_module
    return MANAGER.ast_from_module_name(modname)
  File "C:\Python27\lib\site-packages\astroid\manager.py", line 160, in ast_from_module_name
    return self.ast_from_file(filepath, modname, fallback=False)
  File "C:\Python27\lib\site-packages\astroid\manager.py", line 112, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Python27\lib\site-packages\astroid\builder.py", line 135, in file_build
    return self._post_build(module, encoding)
  File "C:\Python27\lib\site-packages\astroid\builder.py", line 157, in _post_build
    self.delayed_assattr(delayed)
  File "C:\Python27\lib\site-packages\astroid\builder.py", line 209, in delayed_assattr
    for infered in node.expr.infer():
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 124, in _infer_stmts
    for infered in stmt.infer(context):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 86, in cache_generator
    for result in generator:
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 124, in _infer_stmts
    for infered in stmt.infer(context):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 86, in cache_generator
    for result in generator:
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 351, in wrapper
    for node in func(*args, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\inference.py", line 190, in infer_callfunc
    for callee in self.func.infer(context):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 86, in cache_generator
    for result in generator:
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 124, in _infer_stmts
    for infered in stmt.infer(context):
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 86, in cache_generator
    for result in generator:
  File "C:\Python27\lib\site-packages\astroid\bases.py", line 327, in wrapped
    for res in _func(node, context, **kwargs):
  File "C:\Python27\lib\site-packages\astroid\inference.py", line 229, in infer_from
    module = self.do_import_module()
  File "C:\Python27\lib\site-packages\astroid\mixins.py", line 107, in do_import_module
    return mymodule.import_module(modname, level=level)
  File "C:\Python27\lib\site-packages\astroid\scoped_nodes.py", line 431, in import_module
    return MANAGER.ast_from_module_name(modname)
  File "C:\Python27\lib\site-packages\astroid\manager.py", line 160, in ast_from_module_name
    return self.ast_from_file(filepath, modname, fallback=False)
  File "C:\Python27\lib\site-packages\astroid\manager.py", line 112, in ast_from_file
    return AstroidBuilder(self).file_build(filepath, modname)
  File "C:\Python27\lib\site-packages\astroid\builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)
  File "C:\Python27\lib\site-packages\astroid\builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)
  File "C:\Python27\lib\site-packages\astroid\rebuilder.py", line 150, in visit_module
    return self._transform(newnode)
  File "C:\Python27\lib\site-packages\astroid\manager.py", line 337, in transform
    ret = transform_func(node)
  File "C:\Python27\lib\site-packages\pylint_django\transforms\__init__.py", line 29, in set_fake_locals
    module._locals[class_name] = fake._locals[class_name]  # pylint: disable=protected-access
AttributeError: 'Module' object has no attribute '_locals'

**Comment by Alexx-G** [comment]
hmm. Seems like the problem disappeared.
I've upgraded pylint to 1.5.4.
I'll test again tomorrow, but seems like the problem was in pylint.
@meteor5118 Could you try to upgrade pylint and check if the problem was solved?

**Comment by frost-nzcr4** [comment]
Have same problem with pylint 1.4.4, after upgrade to 1.5.4 all works fine.

**Comment by giocalitri** [comment]
as someone else said the problem is with pylint 1.4.4

**Comment by carlio** [comment]
Pretty sure this was fixed in this commit on master: https://github.com/landscapeio/pylint-django/commit/efb3f928e4ab2eb9b48cbb2e150481da99745135 
will add to a new release soon
